version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: hireme_postgres
    environment:
      POSTGRES_DB: hireme_db
      POSTGRES_USER: hireme_user
      POSTGRES_PASSWORD: hireme_password
    ports:
      - '5432:5432'
    volumes:
      - hireme_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  hireme_postgres_data:
